m

diff --git a/bin/hcross b/bin/hcross
--- a/bin/hcross
+++ b/bin/hcross
@@ -1,27 +1,6 @@
 #!/bin/sh -e
-#L:  MIT License
-#L:
-#l:  Copyright (c) 2023 Harkaitz Agirre, harkaitz.aguirre@gmail.com
-#L:
-#L:  Permission is hereby granted, free of charge, to any person obtaining a copy
-#L:  of this software and associated documentation files (the "Software"), to deal
-#L:  in the Software without restriction, including without limitation the rights
-#L:  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-#L:  copies of the Software, and to permit persons to whom the Software is
-#L:  furnished to do so, subject to the following conditions:
-#L:
-#L:  The above copyright notice and this permission notice shall be included in all
-#L:  copies or substantial portions of the Software.
-#L:
-#L:  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-#L:  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-#L:  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-#L:  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-#L:  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-#L:  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
-#L:  SOFTWARE.
 ##:
-#h: Usage: $0 [OPTS...] [CMD...]
+#h: Usage: hcross [OPTS...] [CMD...]
 #h:
 #h: Execute command or function with a toolchain.
 #h:
@@ -39,6 +18,7 @@
 #h:
 #h: -w           : Run command by `build_{CMD}`
 #h: -b           : Bootstrap to the prefix.
+##:
 hcross() (
     local old_env="`export -p`"
     local old_vars="${HBUILD_VARS}" var= line=
@@ -91,16 +71,16 @@ hcross() (
         export HBUILD_TOOCHAIN="${toolchain}"
         local script="`which "${toolchain}-env" 2>/dev/null`"
         if test ! -n "${script}"; then
-            echo "${SCRNAME}: error: Can't find '${toolchain}-env' in path." >&2
+            echo "error: Can't find '${toolchain}-env' in path." >&2
             return 1
         fi
         . "${script}"
         if test ! -n "${HBUILD_TOOLCHAIN}"; then
-            echo "${SCRNAME}: error: The script didn't set HBUILD_TOOLCHAIN." >&2
+            echo "error: The script didn't set HBUILD_TOOLCHAIN." >&2
             return 1
         fi
         if test ! -n "${HBUILD_PREFIX}"; then
-            echo "${SCRNAME}: error: The script didn't set HBUILD_PREFIX." >&2
+            echo "error: The script didn't set HBUILD_PREFIX." >&2
             return 1
         fi
     fi
@@ -137,7 +117,7 @@ hcross() (
     HBUILD_VARS="${old_vars}"
     eval "${old_env}"
 )
-## -----------------------------------------------------------------------------
+## -------------------------------------------------------------------
 hcross_list_programs() {
     printf '%s\n' "${PATH}" | tr ':' '\n' | while read line; do
         if test -d "${line}"; then
@@ -145,20 +125,10 @@ hcross_list_programs() {
         fi
     done
 }
-
-
-
-## -----------------------------------------------------------------------------
-SCRNAME="`basename "$0"`"
-if test @"${SCRNAME}" = @"hcross";then
+## -------------------------------------------------------------------
+if test @"$(basename "$0")" = @"hcross";then
     case "${1}" in
-        ''|-h|--help)
-            sed -n 's/^ *#h: \{0,1\}//p' "$0" | sed "s|\\\$0|${SCRNAME}|g"
-            echo ""
-            sed -n 's/^ *#l: \{0,2\}//p' "$0"
-            ;;
-        *)
-            hcross "$@"
-            ;;
+        ''|-h|--help) sed -n 's/^ *#h: \{0,1\}//p' "$0" ;;
+        *)            hcross "$@"; exit 0;;
     esac
 fi
diff --git a/bin/sysroot-fix b/bin/sysroot-fix
--- a/bin/sysroot-fix
+++ b/bin/sysroot-fix
@@ -1,27 +1,6 @@
 #!/bin/sh -e
-#L:  MIT License
-#L:
-#l:  Copyright (c) 2023 Harkaitz Agirre, harkaitz.aguirre@gmail.com
-#L:
-#L:  Permission is hereby granted, free of charge, to any person obtaining a copy
-#L:  of this software and associated documentation files (the "Software"), to deal
-#L:  in the Software without restriction, including without limitation the rights
-#L:  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-#L:  copies of the Software, and to permit persons to whom the Software is
-#L:  furnished to do so, subject to the following conditions:
-#L:
-#L:  The above copyright notice and this permission notice shall be included in all
-#L:  copies or substantial portions of the Software.
-#L:
-#L:  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-#L:  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-#L:  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-#L:  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-#L:  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-#L:  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
-#L:  SOFTWARE.
 ##:
-#h: Usage: $0 -lkp DIRECTORY...
+#h: Usage: sysroot-fix -lkp DIRECTORY...
 #h:
 #h: -l : Fix links in directory.
 #h: -p : Fix permissions.
@@ -44,15 +23,15 @@ sysroot_fix() {
 sysroot_fix_check_directory() {
     local directory="$1"
     if test ! -d "${directory}";then
-        echo "${SCRNAME}: error: Please specify a directory: ${directory}." >&2
+        echo "error: Please specify a directory: ${directory}." >&2
         return 1
     elif test @"${directory}" = @"/"          ||
          test @"${directory}" = @"/usr"       ||
          test @"${directory}" = @"/usr/local";then
-        echo "${SCRNAME}: error: Refusing to fix ${directory}." >&2
+        echo "error: Refusing to fix ${directory}." >&2
         return 1
     elif test ! -w "${directory}";then
-        echo "${SCRNAME}: error: No permissions to write on ${directory}." >&2
+        echo "error: No permissions to write on ${directory}." >&2
         return 1
     fi
 }
@@ -62,7 +41,7 @@ sysroot_fix_links() {
         local file="`readlink "${link}"`"
         case "${file}" in
             /lib/*|/usr/*)
-                echo "${SCRNAME}: Fixing link ${link} ..."
+                echo "Fixing link ${link} ..."
                 rm -f "${link}"
                 ln -s "${d}${file}" "${link}"
                 ;;
@@ -78,9 +57,9 @@ sysroot_fix_pkgconfig() {
         local p2="`echo "${f}"  | sed 's|/[^/][^/]*/pkgconfig/.*||'`"
         local p1="`echo "${p2}" | sed "s|^${d}||"`"
         if grep "${p2}" "${f}" >/dev/null 2>&1;then
-            echo "${SCRNAME}: Skipping ${f} ..."
+            echo "Skipping ${f} ..."
         else
-            echo "${SCRNAME}: Editing ${f} ..."
+            echo "Editing ${f} ..."
             sed -i".tmp" "s|${p1:-/usr}|${p2}|g" "${f}"
             rm -f "${f}.tmp"
         fi
@@ -93,9 +72,8 @@ sysroot_fix_permissions() {
 
 
 
-## -----------------------------------------------------------------------------
-SCRNAME="`basename "$0"`"
-if test @"${SCRNAME}" = @"sysroot-fix";then
+## -------------------------------------------------------------------
+if test @"$(basename "$0")" = @"sysroot-fix";then
     if test -n "$1";then
         sysroot_fix "$@"
     else
