fixes to hcross

diff --git a/bin/hcross b/bin/hcross
--- a/bin/hcross
+++ b/bin/hcross
@@ -23,13 +23,19 @@
 #L:  LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 #L:  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 #L:  WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
-#h: Usage: $0 [OPTS...] list|show|CMD...
+##:
+#h: Usage: $0 [OPTS...] [CMD...]
+#h:        $0 -w [COLLECTION]
 #h:
 #h: Execute command or function with a toolchain.
 #h:
-#h: -t TOOLCHAIN : Load toolchain.
+#h: -t l|TOOLCHAIN : Load toolchain.
+#h: -v             : Show variables.
+#h:
 #h: -p PREFIX    : Use this prefix.
 #h: -d DESTDIR   : Use this destination directory.
+#h: -D           : When native install dependencies.
+#h:
 #h: -w           : Run command by `build_{CMD}`
 hcross() {
     local old_env="`export -p`"
@@ -37,79 +43,84 @@ hcross() {
     local toolchain="${HBUILD_TOOLCHAIN:-native}"
     HBUILD_VARS= HBUILD_TOOLCHAIN=
     ## Parse command line options.
-    local OPTIND optopt= ops= wrap=
-    while getopts "t:p:d:w" optopt;do # OPTARG
+    local OPTIND optopt= ops= wrap= view=
+    while getopts "t:p:d:Dwv" optopt; do # OPTARG
         case $optopt in
-            t)  local toolchain="${OPTARG}" ;;
-            p)  export HBUILD_PREFIX="${OPTARG}"    ;;
-            d)  export HBUILD_DESTDIR="${OPTARG}"   ;;
+            t)  local toolchain="${OPTARG}"       ;;
+            p)  export HBUILD_PREFIX="${OPTARG}"  ;;
+            d)  export HBUILD_DESTDIR="${OPTARG}" ;;
+            D)  export HBUILD_IDEPS="y"           ;;
             w)  local wrap=y;;
+            v)  local view=y;;
             \?) return 1;;
         esac
     done
     shift $(( $OPTIND - 1 ))
     ## Search and set environment.
-    if test @"${toolchain}" = @"native";then
+    if test @"${toolchain}" = @"native"; then
         export HBUILD_TOOLCHAIN=native
         export HBUILD_PREFIX="${HBUILD_PREFIX:-/usr/local}"
         if test   -e "${HBUILD_DESTDIR}${HBUILD_PREFIX}" && \
-           test ! -w "${HBUILD_DESTDIR}${HBUILD_PREFIX}";then
+           test ! -w "${HBUILD_DESTDIR}${HBUILD_PREFIX}"; then
             export HBUILD_SUDO=sudo
         else
             export HBUILD_SUDO=env
         fi
-    elif test -n "${toolchain}";then
+    elif test @"${toolchain}" = @"l"; then
+        hcross_list_programs | sed -n 's|-env$||p'
+        return 1
+    elif test -n "${toolchain}"; then
         local script="`which "${toolchain}-env" 2>/dev/null`"
-        if test ! -n "${script}";then
-            echo "${SCRNAME}: error: Can't find '${toolchain}-env' in path." >&2
+        if test ! -n "${script}"; then
+            hcross_error "Can't find '${toolchain}-env' in path."
             return 1
         fi
         . "${script}"
-        if test ! -n "${HBUILD_TOOLCHAIN}";then
-            echo "${SCRNAME}: error: The script didn't set HBUILD_TOOLCHAIN." >&2
+        if test ! -n "${HBUILD_TOOLCHAIN}"; then
+            hcross_error "The script didn't set HBUILD_TOOLCHAIN."
             return 1
         fi
-        if test ! -n "${HBUILD_PREFIX}";then
-            echo "${SCRNAME}: error: The script didn't set HBUILD_PREFIX." >&2
+        if test ! -n "${HBUILD_PREFIX}"; then
+            hcross_error "The script didn't set HBUILD_PREFIX."
             return 1
         fi
     fi
-    
-    
+    ## Print variables.
+    if test @"${view}" = @"y"; then
+        for var in HBUILD_PREFIX HBUILD_DESTDIR HBUILD_TOOLCHAIN HBUILD_SUDO HBUILD_IDEPS ${HBUILD_VARS}; do
+            eval 'printf "%-20s : %s\\n" "${var}" "${'"${var}"'}"'
+        done
+        return 0
+    fi
     ## Execute in the changed environment.
-    case "${1}" in
-        ''|show)
-            if test -n "${wrap}";then
-                printf '%s\n' "${PATH}" | tr ':' '\n' | while read line;do
-                    if test -d "${line}";then
-                        ls "${line}" | sed -n 's|build_||p'
-                    fi
-                done
-            else
-                for var in ${HBUILD_VARS};do
-                    eval 'printf "%-20s : %s\\n" "${var}" "${'"${var}"'}"'
-                done
-            fi;;
-        list)
-            printf '%s\n' "${PATH}" | tr ':' '\n' | while read line;do
-                if test -d "${line}";then
-                    ls "${line}"
-                fi
-            done | sed -n 's|-env$||p'
-            ;;
-        *)
-            if test -n "${wrap}";then
-                local cmd="build_`echo "${1}" | tr '-' '_' | tr '/' '_'`"; shift
-                "${cmd}" "$@"
-            else
-                "$@"
-            fi;;
-    esac
+    if test ! -n "${wrap}"; then
+        "$@"
+    elif test -n "${1}"; then
+        local cmd="build_`echo "${1}" | tr '-' '_' | tr '/' '_'`"; shift
+        "${cmd}" "$@"
+    else
+        hcross_list_programs | sed -n 's|^build_||p'
+    fi
     ## Restore environment
-    unset HBUILD_PREFIX HBUILD_DESTDIR HBUILD_TOOLCHAIN HBUILD_SUDO ${HBUILD_VARS}
+    unset HBUILD_PREFIX HBUILD_DESTDIR HBUILD_TOOLCHAIN HBUILD_SUDO HBUILD_IDEPS ${HBUILD_VARS}
     HBUILD_VARS="${old_vars}"
     eval "${old_env}"
 }
+## -----------------------------------------------------------------------------
+hcross_error() {
+    echo "${SCRNAME}: error: $*" >&2
+    return 1
+}
+hcross_list_programs() {
+    printf '%s\n' "${PATH}" | tr ':' '\n' | while read line; do
+        if test -d "${line}"; then
+            ls "${line}"
+        fi
+    done
+}
+
+
+
 ## -----------------------------------------------------------------------------
 SCRNAME="`basename "$0"`"
 if test @"${SCRNAME}" = @"hcross";then
